---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403
