---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_http_port: 8081

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Ensure Jenkins is running on the specified port.
      uri:
        url: "http://127.0.0.1:{{ jenkins_http_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
