---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_url_prefix: /jenkins

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

  post_tasks:
    - name: Ensure Jenkins is running with the specified prefix.
      uri:
        url: "http://127.0.0.1:8080{{ jenkins_url_prefix }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
